### ISSUE TITLE
Typescript defs

### ISSUE THREAD

**Issue by creatorrr** [nicholascelestin/replicate-js#15]
would you consider adding typescript defs? Or perhaps porting the project?

P. S. Happy to help out if it aligns with the goals of this project.

**Comment by nicholascelestin** [comment]
Thanks for the feedback, @creatorrr! Typescript sounds like it'll be important for this library going forward. This is also discussed in #11 .

I'm thinking the eventual goal is to rewrite in TS while trying to:
* Keep the library portable (works in browser, web worker, node, typescript)
* Minimize dependencies
* Keep the build / test process simple

I don't know a lot about TS, so I'm reading up. In the mean time, If you want to take a crack at it, definitely feel free to submit a PR or post your thoughts here.

**Comment by creatorrr** [comment]
Yeah I think, while it takes an initial investment, switching to typescript provides additional safety from errors etc of course, but also extremely useful for existing typescript projects as they can use the types directly. It shouldn't be too difficult to do this. Can take a crack at it over the weekend perhaps
