### ISSUE TITLE
Args not working

### ISSUE THREAD

**Issue by emmajane1313** [nicholascelestin/replicate-js#23]
I'm using this with node for stable diffusion and the api docs say that as well as taking in prompt other args can be inputed like for example num_outputs... however whenever i put any inputs beyond just prompt i get an undefined response. Is there some other way of calling extra parameters that I'm missing?

**Comment by nicholascelestin** [comment]
Hmmm, there is nothing in this library that would remove other args from an input body. Can you paste your code here so that I can take a look?

**Comment by emmajane1313** [comment]
i spoke with replicate it seems an issue from their end with only accepting num_outputs at 1 or 4 or the entire thing errors!
